// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Hanoi from "./Hanoi.res.mjs";
import * as React from "react";
import * as Belt_List from "rescript/lib/es6/belt_List.js";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  var match = React.useState(function () {
        return Hanoi.initState;
      });
  var setCurrentState = match[1];
  var currentState = match[0];
  var movesRef = React.useRef(function () {
        return Hanoi.solve(3, "A", "C", "B");
      });
  var indexRef = React.useRef(0);
  React.useEffect((function () {
          var id = {
            contents: setInterval((function () {
                    
                  }), 1000)
          };
          id.contents = setInterval((function () {
                  var i = indexRef.current;
                  var moves = movesRef.current();
                  var move = Belt_List.get(moves, i);
                  if (move !== undefined) {
                    setCurrentState(function (state) {
                          return Hanoi.applyMove(state, move);
                        });
                    indexRef.current = i + 1 | 0;
                  } else {
                    clearInterval(id.contents);
                  }
                }), 1000);
          return (function () {
                    clearInterval(id.contents);
                  });
        }), []);
  React.useEffect((function () {
          var canvas = document.getElementById("canvas_id");
          if (!(canvas == null)) {
            console.log(currentState);
            Hanoi.draw(currentState, canvas);
          }
          
        }), [currentState]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "What is this about?",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx("canvas", {
                      id: "canvas_id",
                      height: "300",
                      width: "400"
                    })
              ],
              className: "p-6"
            });
}

var make = App;

export {
  make ,
}
/* Hanoi Not a pure module */
