// Generated by ReScript, PLEASE EDIT WITH CARE


var disc_num = 8;

var interval = 100;

var disc_color = "teal";

var rod_color = "maroon";

export {
  disc_num ,
  interval ,
  disc_color ,
  rod_color ,
}
/* No side effect */
